### ISSUE TITLE
Some import errors

### ISSUE THREAD

**Issue by flatsiedatsie** [richmondu/libfaceid#11]
(cv) pi@gateway:~/libfaceid $ python3 agegenderemotion_webcam.py --detector 4 --webcam 0 --resolution 0
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "agegenderemotion_webcam.py", line 3, in <module>
    import cv2
  File "/home/pi/.virtualenvs/cv/lib/python3.5/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
**ImportError: numpy.core.multiarray failed to import**
(cv) pi@gateway:~/libfaceid $ pip3 install -U numpy
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting numpy
Installing collected packages: numpy
  Found existing installation: numpy 1.15.4
    Uninstalling numpy-1.15.4:
      Successfully uninstalled numpy-1.15.4
Successfully installed numpy-1.16.2
(cv) pi@gateway:~/libfaceid $ python3 agegenderemotion_webcam.py --detector 4 --webcam 0 --resolution 0
Traceback (most recent call last):
  File "agegenderemotion_webcam.py", line 6, in <module>
    from libfaceid.encoder  import FaceEncoderModels, FaceEncoder
  File "/home/pi/libfaceid/libfaceid/encoder.py", line 8, in <module>
    from libfaceid.classifier import FaceClassifierModels, FaceClassifier
  File "/home/pi/libfaceid/libfaceid/classifier.py", line 2, in <module>
    from sklearn.svm import SVC
  File "/home/pi/.virtualenvs/cv/lib/python3.5/site-packages/sklearn/svm/__init__.py", line 13, in <module>
    from .classes import SVC, NuSVC, SVR, NuSVR, OneClassSVM, LinearSVC, \
  File "/home/pi/.virtualenvs/cv/lib/python3.5/site-packages/sklearn/svm/classes.py", line 4, in <module>
    from .base import _fit_liblinear, BaseSVC, BaseLibSVM
  File "/home/pi/.virtualenvs/cv/lib/python3.5/site-packages/sklearn/svm/base.py", line 8, in <module>
    from . import libsvm, liblinear
**ImportError: /home/pi/.virtualenvs/cv/lib/python3.5/site-packages/sklearn/svm/liblinear.cpython-35m-arm-linux-gnueabihf.so: undefined symbol: cblas_dnrm2**

**Comment by richmondu** [comment]
Seems there is issue with your scikit-learn version. 
Please install requirements.txt to get the correct versions.
pip install -r requirements.txt
