### ISSUE TITLE
face recognition with liveness detection on pretrained model

### ISSUE THREAD

**Issue by DenisSouth** [richmondu/libfaceid#14]
https://github.com/richmondu/libfaceid#real-time-face-recognition-with-liveness-detection-wa-webcam

i got this error
where are can I find lbph_le.pickle or any data to train the model?

models/training/lbph.yml
Traceback (most recent call last):
  File "E:/colab/pr_test/test.py", line 269, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "E:/colab/pr_test/test.py", line 250, in main
    run(cam_index, cam_resolution)
  File "E:/colab/pr_test/test.py", line 225, in run
    process_livenessdetection(detector, encoder, liveness, cam_index, cam_resolution)
  File "E:/colab/pr_test/test.py", line 89, in process_livenessdetection
    path_training=INPUT_DIR_MODEL_TRAINING, training=False)
  File "E:\colab\pr_test\libfaceid\libfaceid\encoder.py", line 48, in __init__
    self._base = FaceEncoder_LBPH(path, path_training, training)
  File "E:\colab\pr_test\libfaceid\libfaceid\encoder.py", line 100, in __init__
    self._clf.read(self._path_training + OUTPUT_LBPH_CLASSIFIER)
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv_contrib\modules\face\src\facerec.cpp:61: error: (-2:Unspecified error) File can't be opened for reading! in function 'cv::face::FaceRecognizer::read'

[ WARN:0] terminating async callback

**Comment by richmondu** [comment]
Seems you are using OpenCV 4 which apparently does not support LBPH.

You can either change the selected model or update OpenCV version. Refer to requirements.txt for the tested versions of libraries being used.
