### ISSUE TITLE
Import errors

### ISSUE THREAD

**Issue by iamsome1** [richmondu/libfaceid#17]
I cloned your code and installed all packages from your requirements.txt.
Tried "testing_webcam_livenessdetection" from your sample and getting following error:
```
F:\libfaceid-master\libfaceid-master>python testing_webcam_livenessdetection.py --detector 0 --encoder 0 --liveness 0 --webcam 0 --resolution 0
Traceback (most recent call last):
  File "testing_webcam_livenessdetection.py", line 6, in <module>
    from libfaceid.encoder     import FaceEncoderModels, FaceEncoder
  File "F:\libfaceid-master\libfaceid-master\libfaceid\encoder.py", line 6, in <module>
    from imutils import paths      # for FaceEncoderModels.LBPH
ImportError: No module named 'imutils'
```
'imutils' is installed but still this error is there when I run your sample code.

**Comment by colab1590** [comment]
pip install imutils its worked for me.
