### ISSUE TITLE
Errors trying to run certain examples

### ISSUE THREAD

**Issue by jesusrp98** [richmondu/libfaceid#22]
I'm getting an error trying to run certain programs, like `facial_recognition` or `agegenderemotion_webcam`.

Trying to run `facial_recognition` returns this error:
```
$ python facial_recognition.py 
/usr/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Note: Make sure you use the same models for training and testing
Traceback (most recent call last):
  File "facial_recognition.py", line 633, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "facial_recognition.py", line 619, in main
    run()
  File "facial_recognition.py", line 599, in run
    fps = process_facerecognition_livenessdetection_poseagegenderemotion( RESOLUTION_QVGA, None, 0, model_detector=detector, model_recognizer=encoder)
  File "facial_recognition.py", line 349, in process_facerecognition_livenessdetection_poseagegenderemotion
    from libfaceid.pose    import FacePoseEstimatorModels,    FacePoseEstimator
  File "/home/jesus/Documents/tnp/libfaceid/libfaceid/pose.py", line 4, in <module>
    import dlib # for FacePoseEstimatorModels.DLIB68
ImportError: /usr/lib/python3.7/site-packages/dlib.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cblas_dtrsm
```

**Comment by richmondu** [comment]
Hi Jesus, sorry for the late reply. Your error seems to be DLIB related. DLIB is one of the models supported. You can choose either of the two solutions below:

1. Please try fixing your DLIB installation. Also note that I'm not using Python 3.7. Due to several library dependencies, make sure that you install requirements.txt properly and use the Python version I used. Otherwise, compatibility issues will arise.

2. Please don't use the DLIB models.
